;(function(n,d,p){var t=this,u='undefined',e='exports',i;if(typeof module!=u&&module[e]){if(p&&require){for(i in p)t[p[i]]=require(p[i]);}module[e]=d();}else if(typeof define!=u&&define.amd)define(n,(p||[]),d);else{for(i in p)p[i]=t[p[i]];t[n]=d.apply(t,p);}})
('characters/Occupation', function (Settings,Trait) {

    var Occupation = function(type) {
        var _this = this;
        Trait.call(this,getOccupationByCode(type));
    };
	var proto = Occupation.prototype = Object.create(Trait.prototype);

    var occupationTypes = [
	    {code:'actor',name:'Actor',description:''},
	    {code:'alchemist',name:'Alchemist',description:''},
	    {code:'apothecary',name:'Apothecary',description:'Chemist, druggist, pharmacist'},
	    {code:'arbiter',name:'Arbiter',description:'Resolves disputes'},
	    {code:'architect',name:'Architect',description:''},
	    {code:'archivist',name:'Archivist',description:'Record notable events'},
	    {code:'armorer',name:'Armourer',description:'Sells and fits armour'},
	    {code:'assasin',name:'Assasin',description:''},
	    {code:'astrologer',name:'Astrologer',description:''},
	    {code:'bailiff',name:'Bailiff',description:'Serves writs and makes arrests'},
	    {code:'baker',name:'Baker',description:''},
	    {code:'banker',name:'Banker',description:'Stores peoples money'},
	    {code:'barber',name:'Barber',description:''},
	    {code:'barkeep',name:'Barkeep',description:'Bar tender / possibly owner'},
	    {code:'baron',name:'',description:'Feudal landholder'},
	    {code:'barrister',name:'Barrister',description:'Lawyer'},
	    {code:'beeKeeper',name:'Bee keeper',description:''},
	    {code:'bellifounder',name:'Bell maker',description:''},
	    {code:'blacksmith',name:'Blacksmith',description:'Blacksmiths work metal to make things like weapons and armours'}
	    {code:'bonder',name:'Bonder',description:'One who keeps slaves'},
	    {code:'bookBinder',name:'Book binder',description:''},
	    {code:'bookKeeper',name:'Book keeper',description:'Accountant'},
	    {code:'bookSeller',name:'Book seller',description:''},
	    {code:'bowyer',name:'Bow maker',description:''},
	    {code:'breeder',name:'Breeder',description:'Dogs, cats, horses, donkeys, etc.'},
	    {code:'brewer',name:'Brewer',description:''},
	    {code:'butcher',name:'Butcher',description:''},
	    {code:'calligrapher',name:'Calligrapher',description:'Fancy writer'},
	    {code:'candlemaker',name:'Candle maker',description:''},
	    {code:'carpenter',name:'Carpenter',description:'Makes things from wood'},
	    {code:'cartographer',name:'Cartographer',description:'Map maker'},
	    {code:'cartwright',name:'Cartwright',description:'Repairs and builds carts'},
	    {code:'charcoalMaker',name:'Charcoal maker',description:''},
	    {code:'clerk',name:'Clerk',description:'Salesman in a shop / or admin work'},
	    {code:'clockmaker',name:'Clock maker',description:''},
	    {code:'coachman',name:'Coachman',description:'Drives a carriage'},
	    {code:'cobbler',name:'Cobbler',description:'Shoe maker'},
	    {code:'coiner',name:'Coiner',description:'Makes coins at a mint'},
	    {code:'composer',name:'Composer',description:''},
	    {code:'confectioner',name:'Confectioner',description:'Sweets maker'},
	    {code:'cook',name:'Cook',description:''},
	    {code:'cooper',name:'Cooper',description:'Makes wooden barrels'},
	    {code:'coper',name:'Coper',description:'Dealer in dishonest goods'},
	    {code:'coppersmith',name:'Coppersmith',description:'Makes copper items'},
	    {code:'costumer',name:'Costumer',description:''},
	    {code:'courier',name:'Courier',description:''},
	    {code:'cryptographer',name:'Cryptographer',description:'Writes and breaks codes'},
	    {code:'dairyman',name:'Dairyman',description:'Dairy farm worker or product seller'},
	    {code:'dancer',name:'Dancer',description:''},
	    {code:'dentist',name:'Dentist',description:''},
	    {code:'draper',name:'Draper',description:'Fabric dealer'},
	    {code:'dressmaker',name:'Dressmaker',description:''},
	    {code:'dyer',name:'Dyer',description:''},
	    {code:'embroiderer',name:'Embroiderer',description:''},
	    {code:'emissary',name:'Emissary',description:'Representative for someone somewhere else'},
	    {code:'engineer',name:'Engineer',description:''},
	    {code:'engraver',name:'Engraver',description:''},
	    {code:'executioner',name:'Executioner',description:''},
	    {code:'falconer',name:'Falconer',description:'Falcon trainer'},
	    {code:'farmer',name:'Farmer',description:''},
	    {code:'ferrier',name:'Ferrier',description:''},
	    {code:'firstmate',name:'Firstmate',description:'A ships firstmate'},
	    {code:'fisherman',name:'Fisherman',description:''},
	    {code:'fishmonger',name:'Fishmonger',description:'Fish seller'},
	    {code:'fletcher',name:'Fletcher',description:'Arrow maker'},
	    {code:'florist',name:'Florist',description:''},
	    {code:'forrester',name:'Forrester',description:'Game warden or forest ranger'},
	    {code:'gemCutter',name:'Gem cutter',description:''},
	    {code:'glassBlower',name:'Glass blower',description:''},
	    {code:'groom',name:'Groom',description:'Horse keeper / Stable owner'},
	    {code:'groundsKeeper',name:'Grounds keeper',description:'Maintains the outside of an estate'},
	    {code:'harrier',name:'Harrier',description:'Trainer of hunting hounds'},
	    {code:'hatter',name:'Hatter',description:''},
	    {code:'hawker',name:'Hawker',description:'Street seller'},
	    {code:'headmaster',name:'Headmaster',description:'Head of a school'},
	    {code:'healer',name:'Healer',description:''},
	    {code:'herald',name:'Herald',description:'Reporter / witness to important events'},
	    {code:'herder',name:'Herder',description:''},
	    {code:'herbalist',name:'Herbalist',description:'For healing or hurting'},
	    {code:'historian',name:'Historian',description:''},
	    {code:'hoyer',name:'Hoyer',description:'Animal driver'},
	    {code:'importer',name:'Importer',description:''},
	    {code:'innKeeper',name:'Inn keeper',description:''},
	    {code:'interpreter',name:'Interpreter',description:''},
	    {code:'jester',name:'Jester',description:''},
	    {code:'jeweler',name:'Jeweler',description:''},
	    {code:'joiner',name:'Joiner',description:'Cabinet or furniture maker'},
	    {code:'judge',name:'Judge',description:''},
	    {code:'knight',name:'Knight',description:'Nobleman who has been knighted'},
	    {code:'king',name:'King',description:''},
	    {code:'landlord',name:'Landlord',description:''},
	    {code:'leatherWorker',name:'Leather worker',description:''},
	    {code:'limner',name:'Limner',description:'Paints signs and heraldic devices'},
	    {code:'locksmith',name:'Locksmith',description:''},
	    {code:'lumberJack',name:'Lumber jack',description:''},
	    {code:'maidServant',name:'Maid servant',description:''},
	    {code:'manServant',name:'Man servant',description:''},
	    {code:'marbler',name:'Marbler',description:''},
	    {code:'mariner',name:'Mariner',description:'Sailor'},
	    {code:'mason',name:'Mason',description:'Builder in stone'},
	    {code:'mendicant',name:'Mendicant',description:'Beggar for a church'},
	    {code:'mercenary',name:'Mercenary',description:'Killer / protecter for hire'},
	    {code:'mercer',name:'Mercer',description:'Dealer in textile fabrics'},
	    {code:'merchant',name:'Merchant',description:''},
	    {code:'messenger',name:'Messenger',description:''},
	    {code:'metalWorker',name:'Metal worker',description:'Silver, gold, bronze, iron, etc.'},
	    {code:'midshipman',name:'Midshipman ',description:'Officer in training'},
	    {code:'midwife',name:'Midwife',description:''},
	    {code:'militia',name:'Militia',description:'Local police / protection force'},
	    {code:'miller',name:'Miller',description:''},
	    {code:'miner',name:'Miner',description:''},
	    {code:'minstrel',name:'Minstrel',description:'Bard / singer'},
	    {code:'missionary',name:'Missionary',description:'Do-gooder of the church'},
	    {code:'moneyLender',name:'Money lender',description:''},
	    {code:'musician',name:'Musician',description:''},
	    {code:'navigator',name:'Navigator',description:''},
	    {code:'nun',name:'Nun',description:''},
	    {code:'page',name:'Page',description:''},
	    {code:'painter',name:'Painter',description:''},
	    {code:'paperMaker',name:'Paper maker',description:''},
	    {code:'parchmentMaker',name:'Parchment maker',description:''},
	    {code:'performer',name:'Performer',description:''},
	    {code:'perfumer',name:'Perfumer',description:''},
	    {code:'philosopher',name:'Philosopher',description:''},
	    {code:'physicist',name:'Physicist',description:''},
	    {code:'playwright',name:'Playwright',description:''},
	    {code:'poet',name:'poet',description:''},
	    {code:'politician',name:'Politician',description:''},
	    {code:'potter',name:'Potter',description:''},
	    {code:'priest',name:'Priest',description:''},
	    {code:'prince',name:'Prince',description:''},
	    {code:'princess',name:'Princess',description:''},
	    {code:'proselyte',name:'Proselyte',description:'Travels the land converting people to a religion'},
	    {code:'prostitute',name:'Prostitute',description:''},
	    {code:'puppeteer',name:'Puppeteer',description:''},
	    {code:'quarrier',name:'Quarrier',description:'One who cuts stone from natural deposits'},
	    {code:'quarterMaster',name:'Quarter master',description:'Military provisioner'},
	    {code:'queen',name:'Queen',description:''},
	    {code:'rancher',name:'Rancher',description:'Horses, cattle, or other livestock'},
	    {code:'recruiter',name:'Recruiter',description:''},
	    {code:'royalGuard',name:'Royal guard',description:'Protecter of royalty'},
	    {code:'scrivener',name:'Scrivener',description:'Writer, author'},
	    {code:'scullion',name:'Scullion',description:'One who cleans in the kitchen'},
	    {code:'sculptor',name:'Sculptor',description:''},
	    {code:'seamstress',name:'Seamstress',description:''},
	    {code:'shepherd',name:'Sheperd',description:''},
	    {code:'captain',name:'Captain',description:''},
	    {code:'shipWright',name:'Ship wright',description:'One who makes ships and boats'},
	    {code:'slaver',name:'Slaver',description:''},
	    {code:'soapMaker',name:'Soap maker',description:''},
	    {code:'soldier',name:'Soldier',description:'Main military force'},
	    {code:'songWriter',name:'Song writer',description:''},
	    {code:'soothsayer',name:'Soothsayer',description:'A fortune-teller'},
	    {code:'spinner',name:'Spinner',description:'One who spins into wool'},
	    {code:'spy',name:'Spy',description:''},
	    {code:'stableman',name:'Stableman',description:''},
	    {code:'steward',name:'Steward',description:'Servant that oversees the running of a household'},
	    {code:'storyteller',name:'Storyteller',description:''},
	    {code:'scholar',name:'Scholar',description:''},
	    {code:'tailor',name:'Tailor',description:''},
	    {code:'tanner',name:'Tanner',description:'Tans animal skins to make leather'},
	    {code:'taxidermist',name:'Taxidermist',description:'Stuffs / skins animals'},
	    {code:'teacher',name:'Teacher',description:''},
	    {code:'teamster',name:'Teamster',description:'Team of animals driver (like wagon oxes)'},
	    {code:'thatcher',name:'Thatcher',description:'One who thatches roofs'},
	    {code:'tinker',name:'Tinker',description:'A maker in small devices for common use'},
	    {code:'toolmaker',name:'Toolmaker',description:'A smith who makes metal tools'},
	    {code:'torturer',name:'Torturer',description:''},
	    {code:'toyMaker',name:'Toy maker',description:''},
	    {code:'tracker',name:'Tracker',description:''},
	    {code:'trader',name:'Trader',description:''},
	    {code:'trainer',name:'Trainer',description:''},
	    {code:'trapper',name:'Trapper',description:'Captures small animals, deals in furs'},
	    {code:'treasurer',name:'Treasurer',description:''},
	    {code:'undertaker',name:'Undertaker',description:''},
	    {code:'vintner',name:'Vintner',description:'Wine maker'},
	    {code:'wainWright',name:'Wainwright',description:'Maker and repairer of wagons'},
	    {code:'watchman',name:'watchman',description:''},
	    {code:'weaver',name:'Weaver',description:''},
	    {code:'wheelwright',name:'Wheelwright',description:''},
	    {code:'woodCarver',name:'Wood carver',description:''},
    ];

	var _occupationTypeHash = {};
	var _occupationOptions = [];

	for (var t=0;t<_occupationTypes.length;t++) {
		_occupationTypesHash[_occupationTypes[t].code] = t;
		_occupationOptions.push(_occupationTypes[t].code);
	}

	function getOccupationByCode(code) {
		return _occupationTypes[_occupationTypesHash[code]];
	};

	proto.getOccupationOptions = function() {
		return _occupationOptions.slice();
	};

	return Occupation;
},['Settings','Trait']);